using System.Globalization;

namespace CoolJob.Helpers
{
    public static class T
    {
        private static readonly Dictionary<string, Dictionary<string, string>> _texts = new()
        {
            ["ru"] = new()
            {
                ["Layout.Title"] = "CoolJob — Платформа для поиска работы",
                ["Layout.Logo"] = "CoolJob",
                ["Layout.Slogan"] = "Твой старт карьеры в университете",
                ["Layout.Welcome"] = "Привет",
                ["Layout.Login"] = "Войти",
                ["Layout.Register"] = "Регистрация",
                ["Layout.Nav.Home"] = "Главная",
                ["Layout.Nav.Jobs"] = "Вакансии",
                ["Layout.Nav.MyApplications"] = "Мои отклики",
                ["Layout.Nav.Profile"] = "Профиль",
                ["Layout.Nav.Logout"] = "Выйти",
                ["Layout.Footer.About"] = "Платформа для поиска работы и стажировок в университете",
                ["Layout.Footer.Contacts"] = "Контакты",
                ["Layout.Footer.Social"] = "Соцсети",
                ["Layout.Footer.Copyright"] = "Все права защищены",
                
                ["Home.Hero.Title"] = "Найди идеальную работу в кампусе и за его пределами!",
                ["Home.Hero.Subtitle"] = "Стажировки, подработка и исследовательские проекты от университета и партнёров",
                ["Home.Hero.SearchBtn"] = "Начать поиск",
                ["Home.Hero.PartnersBtn"] = "Партнёрские вакансии",
                ["Home.Feature.FastSearch.Title"] = "Быстрый поиск",
                ["Home.Feature.FastSearch.Desc"] = "Фильтруй вакансии по факультету, навыкам и типу занятости",
                ["Home.Feature.Apply.Title"] = "Подача заявок",
                ["Home.Feature.Apply.Desc"] = "Отправляй резюме и сопроводительные письма в пару кликов",
                ["Home.Feature.Notifications.Title"] = "Умные уведомления",
                ["Home.Feature.Notifications.Desc"] = "Получай оповещения о новых подходящих вакансиях",
                ["Home.Vacancies.Title"] = "Свежие вакансии",
                ["Home.Vacancies.SeeAll"] = "Все вакансии →",
                
                ["Jobs.Title"] = "Вакансии",
                ["Jobs.Header"] = "Доступные вакансии",
                ["Jobs.SearchPlaceholder"] = "Поиск...",
                ["Jobs.AllTypes"] = "Все типы",
                ["Jobs.SearchBtn"] = "Найти",
                ["Jobs.Apply"] = "Откликнуться",
                ["Jobs.Details"] = "Подробнее",
                ["Jobs.SalaryNotSpecified"] = "З/П не указана",
                
                ["Jobs.Details.Title"] = "Описание вакансии",
                ["Jobs.Details.Apply"] = "Откликнуться",
                ["Jobs.Details.LoginToApply"] = "Войдите, чтобы откликнуться",
                ["Jobs.Details.Back"] = "Назад к списку",
                ["Jobs.Details.Published"] = "Опубликовано",
                
                ["Applications.My.Title"] = "Мои отклики",
                ["Applications.My.Employer"] = "Работодатель",
                ["Applications.My.Date"] = "Дата отклика",
                ["Applications.My.CoverLetter"] = "Сопроводительное письмо",
                ["Applications.My.Details"] = "Подробнее",
                ["Applications.My.Withdraw"] = "Отозвать",
                
                ["Applications.Details.Title"] = "Детали отклика",
                ["Applications.Details.Vacancy"] = "Вакансия",
                ["Applications.Details.Employer"] = "Работодатель",
                ["Applications.Details.Status"] = "Статус",
                ["Applications.Details.ApplyDate"] = "Дата отклика",
                ["Applications.Details.CoverLetter"] = "Сопроводительное письмо",
                ["Applications.Details.Resume"] = "Резюме",
                ["Applications.Details.ViewResume"] = "Просмотреть резюме",
                ["Applications.Details.Back"] = "Назад к списку",
                
                ["Profile.Title"] = "Мой профиль",
                ["Profile.Edit"] = "Редактировать",
                ["Profile.Name"] = "Имя",
                ["Profile.Email"] = "Email",
                ["Profile.Faculty"] = "Факультет",
                ["Profile.NotSpecified"] = "Не указан",
                ["Profile.MyApplications"] = "Мои заявки",
                ["Profile.NoApplications"] = "У вас пока нет активных заявок",
                ["Profile.FindJobs"] = "Найти вакансии",
                
                ["Profile.Edit.Title"] = "Редактирование профиля",
                ["Profile.Edit.FirstName"] = "Имя",
                ["Profile.Edit.LastName"] = "Фамилия",
                ["Profile.Edit.Faculty"] = "Факультет",
                ["Profile.Edit.Save"] = "Сохранить",
                ["Profile.Edit.Cancel"] = "Отмена",
                
                ["Auth.Login.Title"] = "Вход в систему",
                ["Auth.Login.Header"] = "Вход в CoolJob",
                ["Auth.Login.Email"] = "Email",
                ["Auth.Login.Password"] = "Пароль",
                ["Auth.Login.Remember"] = "Запомнить меня?",
                ["Auth.Login.Submit"] = "Войти",
                ["Auth.Login.ForgotPassword"] = "Забыли пароль?",
                ["Auth.Login.ToRegister"] = "Регистрация",
                
                ["Auth.AccessDenied.Title"] = "Доступ запрещен",
                ["Auth.AccessDenied.Header"] = "Доступ запрещен",
                ["Auth.AccessDenied.Message"] = "У вас недостаточно прав для просмотра этой страницы",
                ["Auth.AccessDenied.Home"] = "На главную",
                
                ["Register.Title"] = "Регистрация",
                ["Register.Header"] = "Регистрация",
                ["Register.Email"] = "почта",
                ["Register.Password"] = "пароль",
                ["Register.ConfirmPassword"] = "повторите пароль",
                ["Register.FirstName"] = "введите имя",
                ["Register.LastName"] = "введите фамилию",
                ["Register.Submit"] = "Зарегистрироваться",
                ["Register.EmailPlaceholder"] = "example@email.com",
                ["Register.PasswordPlaceholder"] = "Не менее 6 символов",
                ["Register.ConfirmPlaceholder"] = "Повторите пароль",
                ["Register.FirstNamePlaceholder"] = "Иван",
                ["Register.LastNamePlaceholder"] = "Иванов",
                
                ["Validation.Required"] = "Обязательное поле",
                ["Validation.InvalidEmail"] = "Некорректный формат Email",
                ["Validation.PasswordMin"] = "Пароль должен содержать минимум 6 символов",
                ["Validation.PasswordsMatch"] = "Пароли не совпадают",
                ["Validation.UserExists"] = "Пользователь с таким email уже существует",
                
                ["Status.Pending"] = "На рассмотрении",
                ["Status.Accepted"] = "Принято",
                ["Status.Rejected"] = "Отклонено",
                ["Status.Interview"] = "На собеседовании",
                
                ["JobType.FullTime"] = "Полный день",
                ["JobType.PartTime"] = "Частичная занятость",
                ["JobType.Internship"] = "Стажировка",
                ["JobType.Remote"] = "Удалённая работа",
            },
            ["en"] = new()
            {
                ["Layout.Title"] = "CoolJob — Job Search Platform",
                ["Layout.Logo"] = "CoolJob",
                ["Layout.Slogan"] = "Start your career at university",
                ["Layout.Welcome"] = "Welcome",
                ["Layout.Login"] = "Login",
                ["Layout.Register"] = "Register",
                ["Layout.Nav.Home"] = "Home",
                ["Layout.Nav.Jobs"] = "Jobs",
                ["Layout.Nav.MyApplications"] = "My Applications",
                ["Layout.Nav.Profile"] = "Profile",
                ["Layout.Nav.Logout"] = "Logout",
                ["Layout.Footer.About"] = "Platform for finding jobs and internships at university",
                ["Layout.Footer.Contacts"] = "Contacts",
                ["Layout.Footer.Social"] = "Social",
                ["Layout.Footer.Copyright"] = "All rights reserved",
                
                ["Home.Hero.Title"] = "Find your perfect job on campus and beyond!",
                ["Home.Hero.Subtitle"] = "Internships, part-time jobs and research projects from the university and partners",
                ["Home.Hero.SearchBtn"] = "Start searching",
                ["Home.Hero.PartnersBtn"] = "Partner vacancies",
                ["Home.Feature.FastSearch.Title"] = "Fast search",
                ["Home.Feature.FastSearch.Desc"] = "Filter jobs by faculty, skills and employment type",
                ["Home.Feature.Apply.Title"] = "Easy applications",
                ["Home.Feature.Apply.Desc"] = "Send resumes and cover letters in a couple of clicks",
                ["Home.Feature.Notifications.Title"] = "Smart notifications",
                ["Home.Feature.Notifications.Desc"] = "Get alerts about new suitable vacancies",
                ["Home.Vacancies.Title"] = "Fresh vacancies",
                ["Home.Vacancies.SeeAll"] = "All jobs →",
                
                ["Jobs.Title"] = "Jobs",
                ["Jobs.Header"] = "Available vacancies",
                ["Jobs.SearchPlaceholder"] = "Search...",
                ["Jobs.AllTypes"] = "All types",
                ["Jobs.SearchBtn"] = "Search",
                ["Jobs.Apply"] = "Apply",
                ["Jobs.Details"] = "Details",
                ["Jobs.SalaryNotSpecified"] = "Salary not specified",
                
                ["Jobs.Details.Title"] = "Job description",
                ["Jobs.Details.Apply"] = "Apply now",
                ["Jobs.Details.LoginToApply"] = "Login to apply",
                ["Jobs.Details.Back"] = "Back to list",
                ["Jobs.Details.Published"] = "Published",
                
                ["Applications.My.Title"] = "My applications",
                ["Applications.My.Employer"] = "Employer",
                ["Applications.My.Date"] = "Application date",
                ["Applications.My.CoverLetter"] = "Cover letter",
                ["Applications.My.Details"] = "Details",
                ["Applications.My.Withdraw"] = "Withdraw",
                
                ["Applications.Details.Title"] = "Application details",
                ["Applications.Details.Vacancy"] = "Vacancy",
                ["Applications.Details.Employer"] = "Employer",
                ["Applications.Details.Status"] = "Status",
                ["Applications.Details.ApplyDate"] = "Application date",
                ["Applications.Details.CoverLetter"] = "Cover letter",
                ["Applications.Details.Resume"] = "Resume",
                ["Applications.Details.ViewResume"] = "View resume",
                ["Applications.Details.Back"] = "Back to list",
                
                ["Profile.Title"] = "My profile",
                ["Profile.Edit"] = "Edit",
                ["Profile.Name"] = "Name",
                ["Profile.Email"] = "Email",
                ["Profile.Faculty"] = "Faculty",
                ["Profile.NotSpecified"] = "Not specified",
                ["Profile.MyApplications"] = "My applications",
                ["Profile.NoApplications"] = "You have no active applications yet",
                ["Profile.FindJobs"] = "Find jobs",
                
                ["Profile.Edit.Title"] = "Edit profile",
                ["Profile.Edit.FirstName"] = "First name",
                ["Profile.Edit.LastName"] = "Last name",
                ["Profile.Edit.Faculty"] = "Faculty",
                ["Profile.Edit.Save"] = "Save",
                ["Profile.Edit.Cancel"] = "Cancel",
                
                ["Auth.Login.Title"] = "Login",
                ["Auth.Login.Header"] = "Login to CoolJob",
                ["Auth.Login.Email"] = "Email",
                ["Auth.Login.Password"] = "Password",
                ["Auth.Login.Remember"] = "Remember me?",
                ["Auth.Login.Submit"] = "Login",
                ["Auth.Login.ForgotPassword"] = "Forgot password?",
                ["Auth.Login.ToRegister"] = "Register",
                
                ["Auth.AccessDenied.Title"] = "Access denied",
                ["Auth.AccessDenied.Header"] = "Access denied",
                ["Auth.AccessDenied.Message"] = "You don't have enough permissions to view this page",
                ["Auth.AccessDenied.Home"] = "Go to home",
                
                ["Register.Title"] = "Register",
                ["Register.Header"] = "Register",
                ["Register.Email"] = "email",
                ["Register.Password"] = "password",
                ["Register.ConfirmPassword"] = "confirm password",
                ["Register.FirstName"] = "enter first name",
                ["Register.LastName"] = "enter last name",
                ["Register.Submit"] = "Register",
                ["Register.EmailPlaceholder"] = "example@email.com",
                ["Register.PasswordPlaceholder"] = "At least 6 characters",
                ["Register.ConfirmPlaceholder"] = "Confirm password",
                ["Register.FirstNamePlaceholder"] = "John",
                ["Register.LastNamePlaceholder"] = "Doe",
                
                ["Validation.Required"] = "This field is required",
                ["Validation.InvalidEmail"] = "Invalid email format",
                ["Validation.PasswordMin"] = "Password must be at least 6 characters",
                ["Validation.PasswordsMatch"] = "Passwords do not match",
                ["Validation.UserExists"] = "A user with this email already exists",
                
                ["Status.Pending"] = "Under review",
                ["Status.Accepted"] = "Accepted",
                ["Status.Rejected"] = "Rejected",
                ["Status.Interview"] = "Interview",
                
                ["JobType.FullTime"] = "Full-time",
                ["JobType.PartTime"] = "Part-time",
                ["JobType.Internship"] = "Internship",
                ["JobType.Remote"] = "Remote",
            }
        };

        public static string Get(string key)
        {
            var lang = CultureInfo.CurrentCulture.Name.StartsWith("ru") ? "ru" : "en";
            return _texts.TryGetValue(lang, out var dict) && dict.TryGetValue(key, out var val) 
                ? val 
                : key;
        }
    }
}